services:
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
      - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 10s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
      - 5672:5672
      - 15672:15672

  gateway:
    build:
      context: ./src
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=gateway
      - SERVER_PORT=5678
      - MOM_HOST=rabbitmq
      - OUTPUT_QUEUE=transfer_data_controller_queue
      - INPUT_QUEUE=gateway_results_queue

  transfer_data_controller:
    build: &entity_build
      context: ./src
      dockerfile: entities/Dockerfile
    container_name: transfer_data_controller
    depends_on: &rabbitmq_dependency
      rabbitmq:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=TransferDataController
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=transfer_data_controller_queue
      - OUTPUT_QUEUE=currency_filter_queue

  currency_filter:
    build: *entity_build
    container_name: currency_filter
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=CurrencyFilter
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=currency_filter_queue
      - OUTPUT_QUEUE=amount_filter_queue

  amount_filter:
    build: *entity_build
    container_name: amount_filter
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=AmountFilter
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=amount_filter_queue
      - OUTPUT_QUEUE=data_per_bank_redirector_queue

  data_per_bank_redirector:
    build: *entity_build
    container_name: data_per_bank_redirector
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=DataPerBankRedirector
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=data_per_bank_redirector_queue
      - OUTPUT_QUEUE=map_max_amount_per_bank_queue

  map_max_amount_per_bank:
    build: *entity_build
    container_name: map_max_amount_per_bank
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=MapMaxAmountPerBank
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=map_max_amount_per_bank_queue
      - OUTPUT_QUEUE=join_max_amount_per_bank_queue

  join_max_amount_per_bank:
    build: *entity_build
    container_name: join_max_amount_per_bank
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=JoinMaxAmountPerBank
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=join_max_amount_per_bank_queue
      - OUTPUT_QUEUE=filter_date_window_queue

  filter_date_window:
    build: *entity_build
    container_name: filter_date_window
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=FilterDateWindow
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=filter_date_window_queue
      - OUTPUT_QUEUE=dynamic_amount_filter_queue

  dynamic_amount_filter:
    build: *entity_build
    container_name: dynamic_amount_filter
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=DynamicAmountFilter
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=dynamic_amount_filter_queue
      - OUTPUT_QUEUE=map_average_queue

  map_average:
    build: *entity_build
    container_name: map_average
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=MapAverage
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=map_average_queue
      - OUTPUT_QUEUE=join_average_queue

  join_average:
    build: *entity_build
    container_name: join_average
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=JoinAverage
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=join_average_queue
      - OUTPUT_QUEUE=map_scatter_gather_queue

  map_scatter_gather:
    build: *entity_build
    container_name: map_scatter_gather
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=MapScatterGather
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=map_scatter_gather_queue
      - OUTPUT_QUEUE=aggregation_scatter_gather_queue

  aggregation_scatter_gather:
    build: *entity_build
    container_name: aggregation_scatter_gather
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=AggregationScatterGather
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=aggregation_scatter_gather_queue
      - OUTPUT_QUEUE=join_scatter_gather_queue

  join_scatter_gather:
    build: *entity_build
    container_name: join_scatter_gather
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=JoinScatterGather
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=join_scatter_gather_queue
      - OUTPUT_QUEUE=pay_format_filter_queue

  pay_format_filter:
    build: *entity_build
    container_name: pay_format_filter
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=PayFormatFilter
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=pay_format_filter_queue
      - OUTPUT_QUEUE=currency_converter_queue

  currency_converter:
    build: *entity_build
    container_name: currency_converter
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=CurrencyConverter
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=currency_converter_queue
      - OUTPUT_QUEUE=transfer_counter_queue

  transfer_counter:
    build: *entity_build
    container_name: transfer_counter
    depends_on: *rabbitmq_dependency
    environment:
      - PYTHONUNBUFFERED=1
      - PROCESSING_DELAY_SECONDS=1
      - ENTITY_CLASS=TransferCounter
      - MOM_HOST=rabbitmq
      - INPUT_QUEUE=transfer_counter_queue
      - OUTPUT_QUEUE=gateway_results_queue

  client:
    build:
      context: ./src
      dockerfile: client/Dockerfile
    container_name: client
    depends_on:
      - gateway
      - transfer_data_controller
      - currency_filter
      - amount_filter
      - data_per_bank_redirector
      - map_max_amount_per_bank
      - join_max_amount_per_bank
      - filter_date_window
      - dynamic_amount_filter
      - map_average
      - join_average
      - map_scatter_gather
      - aggregation_scatter_gather
      - join_scatter_gather
      - pay_format_filter
      - currency_converter
      - transfer_counter
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=gateway
      - SERVER_PORT=5678
      - MESSAGE=mensaje de prueba
